### PR TITLE
Fixed 'location block outside server block' error.

### PR DESCRIPTION
**Pull request by fluchtkapsel**
Added ssl_only => $real_server_ssl to avoid having a location block outside of the server block.

### CODE REVIEW

**Comment by pgassmann** [comment]
can you explain a bit more what the issue is? how did you use this module? what was the result?

**Comment by pgassmann** [comment]
can you explain a bit more what the issue is? how did you use this module? what was the result?

This seems wrong to me. letsencrypt challenge is done by HTTP, not HTTPS. so `ssl_only` should never be used for the letsencrypt challenge webroot.

**Comment by fluchtkapsel** [comment]
I'll write in English but German is my native tongue, so pardon me for wrong wording or stuff …

I spent a few hours trying to debug a defective nginx config. Everytime I tried this module nginx refused to start because of a location block outside a server block.

In our setup at Wikimedia Deutschland we use an LXC container acting as a reverse proxy for web services running in different other containers. This reverse proxy also does all the TLS/SSL. There is no webroot in this container. For using your module I created a webroot at /srv/http/letsencrypt:
```
	file { 'webroot':
		path => '/srv/http/letsencrypt',
		ensure => 'directory',
	}
```
Then, I initialize the letsencrypt module:
```
	class { 'letsencrypt':
		package_ensure => 'latest',
		config => {
			email => 'noc@wikimedia.de',
			server => 'https://acme-v01.api.letsencrypt.org/directory',
#			server => 'https://acme-staging.api.letsencrypt.org/directory'
		},
	}
```
So far, everything's fine. Usually, when not using Let's Encrypt (because we paid for a wildcard certificate some time ago), we just generate a server block that listens on port 80 and 301s to https on port 443, e.g.:
```
	nginx::resource::server { "blog80":
		listen_port => 80,
		ensure => present,
		access_log => "off",
		error_log => "off",
		server_name => ["blog.wikimedia.de"],
		server_cfg_append => {
			"return" =>  '301 https://blog.wikimedia.de$request_uri'
		}
	}
```
Accordingly, there's a server block listening on port 443: ```
```
	nginx::resource::server {"blog443":
		ensure => present,
		server_name => ["blog.wikimedia.de"],
		listen_port => 443,
		ssl => true,
		ssl_port => 443,
		ssl_key => "<path to key>",
		ssl_cert => "<path to cert>",
		proxy => "http://[…]",
		access_log => "off",
		error_log => "off",

		location_raw_append => 'proxy_pass_header	Set-Cookie;
    proxy_set_header	X-Forwarded-Host $host;
    proxy_set_header	X-Forwarded-Server $host;
    proxy_set_header	X-Forwarded-Proto $scheme;
                        ',
	}
```
As you can see, there's no default server catching all server names – I tried _ (underscore) as mentioned in the nginx documentation but it didn't work. I had to use this config:
```
  	nginx::resource::server { "default80":
		listen_port => 80,
		ensure => present,
		server_name => ["_", "wikiba.se", "www.wikiba.se"],
		server_cfg_append => {
			"return" =>  '301 https://$host$request_uri'
		}
	}
	nginx::resource::server {"wikibase443":
		ensure => present,
		server_name => ["wikiba.se", "www.wikiba.se"],
		listen_port => 443,
		ssl => true,
		ssl_port => 443,
		ssl_key => "/etc/letsencrypt/live/wikibase443/privkey.pem",
		ssl_cert => "/etc/letsencrypt/live/wikibase443/fullchain.pem",
		proxy => "http://10.0.6.207:80",
		access_log => "off",
		error_log => "off",
#		rewrite_to_https => true,
	}
```
with every domain explicitly specified. rewrite_to_https didn't show any effect.

Without changing your module it always created a location block outside of wikibase443's server block and inside of it. With setting it hard to false there was none inside but only outside, with setting it hard to true it was inside but none in default80. So I resorted to have it created according to whether ssl is set or not. And this worked finally.

**Comment by pgassmann** [comment]
`nginx::resource::server` by default creates http and https servers if `ssl => true` ans `ssl_only`  is not set to true

I'm not actively using puppet anymore, so I will spend too much time on this. If you want to set ssl_only => true, please update the pull request to add `ssl_only` as an optional parameter (default to `undef`), then you can set it without affecting other users.

**Pull request closed without merging**
